import { PlatformRole } from "./types";
import { PLATFORM_PERMISSIONS, type PlatformPermission } from "./platformPermissions";

const ALL_PLATFORM_PERMISSIONS: readonly PlatformPermission[] = Object.freeze(
    Object.values(PLATFORM_PERMISSIONS)
);

/**
 * Concrete Role-to-Permission Matrix
 * Encoded as immutable data per locked Architecture Specification (Phase 1.19.1 Section 2.3).
 */
export const PLATFORM_ROLE_PERMISSIONS: Record<
    PlatformRole,
    readonly PlatformPermission[]
> = {
    PLATFORM_OWNER: ALL_PLATFORM_PERMISSIONS,

    PLATFORM_ADMIN: Object.freeze([
        PLATFORM_PERMISSIONS.WORKSPACES_VIEW,
        PLATFORM_PERMISSIONS.WORKSPACES_CREATE,
        PLATFORM_PERMISSIONS.WORKSPACES_UPDATE,
        PLATFORM_PERMISSIONS.WORKSPACES_SUSPEND,
        PLATFORM_PERMISSIONS.WORKSPACES_SUPPORT_VIEW,
        PLATFORM_PERMISSIONS.BILLING_VIEW,
        PLATFORM_PERMISSIONS.BILLING_MANAGE_PLANS,
        PLATFORM_PERMISSIONS.BILLING_OVERRIDE_ENTITLEMENTS,
        PLATFORM_PERMISSIONS.OPERATORS_VIEW,
        PLATFORM_PERMISSIONS.CONFIG_VIEW,
        PLATFORM_PERMISSIONS.CONFIG_MANAGE_FLAGS,
        PLATFORM_PERMISSIONS.CONFIG_UPDATE_SETTINGS,
        PLATFORM_PERMISSIONS.DEVELOPER_VIEW_APPS,
        PLATFORM_PERMISSIONS.DEVELOPER_REVOKE_KEYS,
        PLATFORM_PERMISSIONS.DEVELOPER_MANAGE_WEBHOOKS,
        PLATFORM_PERMISSIONS.INTEGRATIONS_REVOKE_CREDENTIALS,
        PLATFORM_PERMISSIONS.OPERATIONS_VIEW_QUEUES,
        PLATFORM_PERMISSIONS.OPERATIONS_RETRY_JOBS,
        PLATFORM_PERMISSIONS.AUDIT_VIEW,
    ]),

    PLATFORM_SUPPORT: Object.freeze([
        PLATFORM_PERMISSIONS.WORKSPACES_VIEW,
        PLATFORM_PERMISSIONS.WORKSPACES_SUPPORT_VIEW,
        PLATFORM_PERMISSIONS.BILLING_VIEW,
        PLATFORM_PERMISSIONS.CONFIG_VIEW,
        PLATFORM_PERMISSIONS.DEVELOPER_VIEW_APPS,
    ]),

    PLATFORM_OPERATIONS: Object.freeze([
        PLATFORM_PERMISSIONS.WORKSPACES_VIEW,
        PLATFORM_PERMISSIONS.CONFIG_VIEW,
        PLATFORM_PERMISSIONS.CONFIG_UPDATE_SETTINGS,
        PLATFORM_PERMISSIONS.DEVELOPER_MANAGE_WEBHOOKS,
        PLATFORM_PERMISSIONS.OPERATIONS_VIEW_QUEUES,
        PLATFORM_PERMISSIONS.OPERATIONS_RETRY_JOBS,
        PLATFORM_PERMISSIONS.OPERATIONS_PURGE_STALE,
    ]),

    PLATFORM_SECURITY: Object.freeze([
        PLATFORM_PERMISSIONS.WORKSPACES_VIEW,
        PLATFORM_PERMISSIONS.WORKSPACES_SUPPORT_VIEW,
        PLATFORM_PERMISSIONS.OPERATORS_VIEW,
        PLATFORM_PERMISSIONS.CONFIG_VIEW,
        PLATFORM_PERMISSIONS.DEVELOPER_VIEW_APPS,
        PLATFORM_PERMISSIONS.DEVELOPER_REVOKE_KEYS,
        PLATFORM_PERMISSIONS.DEVELOPER_MANAGE_WEBHOOKS,
        PLATFORM_PERMISSIONS.INTEGRATIONS_REVOKE_CREDENTIALS,
        PLATFORM_PERMISSIONS.AUDIT_VIEW,
        PLATFORM_PERMISSIONS.SECURITY_INSPECT_SESSIONS,
        PLATFORM_PERMISSIONS.SECURITY_TERMINATE_SESSIONS,
    ]),

    PLATFORM_BILLING: Object.freeze([
        PLATFORM_PERMISSIONS.WORKSPACES_VIEW,
        PLATFORM_PERMISSIONS.BILLING_VIEW,
        PLATFORM_PERMISSIONS.BILLING_MANAGE_PLANS,
        PLATFORM_PERMISSIONS.BILLING_OVERRIDE_ENTITLEMENTS,
        PLATFORM_PERMISSIONS.BILLING_SYNC_GATEWAY,
    ]),
};
