import type {
    MembershipRole,
} from "@/generated/prisma/client";

import {
    PERMISSIONS,
    type Permission,
} from "./permissions";

const FULL_PERMISSIONS: Permission[] =
    Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<
    MembershipRole,
    readonly Permission[]
> = {
    OWNER: FULL_PERMISSIONS,

    ADMIN: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,
        PERMISSIONS.CUSTOMERS_DELETE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,
        PERMISSIONS.WORK_ORDERS_COMPLETE,
        PERMISSIONS.WORK_ORDERS_DELETE,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.MEMBERS_VIEW,
        PERMISSIONS.MEMBERS_INVITE,
        PERMISSIONS.MEMBERS_UPDATE,
        PERMISSIONS.MEMBERS_REMOVE,

        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_UPDATE,

        PERMISSIONS.SERVICE_CATALOG_VIEW,
        PERMISSIONS.SERVICE_CATALOG_CREATE,
        PERMISSIONS.SERVICE_CATALOG_UPDATE,
        PERMISSIONS.SERVICE_CATALOG_DELETE,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_CREATE,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_TRANSFER,
        PERMISSIONS.ASSETS_STATUS_CHANGE,
        PERMISSIONS.ASSETS_RETIRE,
        PERMISSIONS.ASSETS_DELETE,
        PERMISSIONS.ASSET_CATEGORIES_MANAGE,

        PERMISSIONS.BILLING_VIEW,
        PERMISSIONS.BILLING_MANAGE,

        PERMISSIONS.PARTS_VIEW,
        PERMISSIONS.PARTS_CREATE,
        PERMISSIONS.PARTS_UPDATE,
        PERMISSIONS.PARTS_DELETE,
        PERMISSIONS.INVENTORY_VIEW,
        PERMISSIONS.INVENTORY_RECEIVE,
        PERMISSIONS.INVENTORY_TRANSFER,
        PERMISSIONS.INVENTORY_ADJUST,
        PERMISSIONS.INVENTORY_RESERVE,
        PERMISSIONS.INVENTORY_CONSUME,
        PERMISSIONS.INVENTORY_RETURN,
        PERMISSIONS.INVENTORY_LOCATIONS_VIEW,
        PERMISSIONS.INVENTORY_LOCATIONS_MANAGE,

        PERMISSIONS.QUOTES_VIEW,
        PERMISSIONS.QUOTES_CREATE,
        PERMISSIONS.QUOTES_UPDATE,
        PERMISSIONS.QUOTES_DELETE,
        PERMISSIONS.QUOTES_SEND,
        PERMISSIONS.QUOTES_APPROVE,
        PERMISSIONS.QUOTES_REJECT,
        PERMISSIONS.QUOTES_CONVERT,

        PERMISSIONS.INVOICES_VIEW,
        PERMISSIONS.INVOICES_CREATE,
        PERMISSIONS.INVOICES_UPDATE,
        PERMISSIONS.INVOICES_DELETE,
        PERMISSIONS.INVOICES_ISSUE,
        PERMISSIONS.INVOICES_VOID,
        PERMISSIONS.PAYMENTS_VIEW,
        PERMISSIONS.PAYMENTS_CREATE,
        PERMISSIONS.PAYMENTS_VOID,

        PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
        PERMISSIONS.REPORTS_VIEW_FINANCIAL,
        PERMISSIONS.REPORTS_VIEW_TECHNICIAN,
        PERMISSIONS.REPORTS_EXPORT,
    ],

    MANAGER: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,
        PERMISSIONS.WORK_ORDERS_COMPLETE,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.MEMBERS_VIEW,

        PERMISSIONS.SETTINGS_VIEW,

        PERMISSIONS.SERVICE_CATALOG_VIEW,
        PERMISSIONS.SERVICE_CATALOG_CREATE,
        PERMISSIONS.SERVICE_CATALOG_UPDATE,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_CREATE,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_TRANSFER,
        PERMISSIONS.ASSETS_STATUS_CHANGE,
        PERMISSIONS.ASSETS_RETIRE,
        PERMISSIONS.ASSET_CATEGORIES_MANAGE,

        PERMISSIONS.PARTS_VIEW,
        PERMISSIONS.PARTS_CREATE,
        PERMISSIONS.PARTS_UPDATE,
        PERMISSIONS.INVENTORY_VIEW,
        PERMISSIONS.INVENTORY_RECEIVE,
        PERMISSIONS.INVENTORY_TRANSFER,
        PERMISSIONS.INVENTORY_ADJUST,
        PERMISSIONS.INVENTORY_RESERVE,
        PERMISSIONS.INVENTORY_CONSUME,
        PERMISSIONS.INVENTORY_RETURN,
        PERMISSIONS.INVENTORY_LOCATIONS_VIEW,
        PERMISSIONS.INVENTORY_LOCATIONS_MANAGE,

        PERMISSIONS.QUOTES_VIEW,
        PERMISSIONS.QUOTES_CREATE,
        PERMISSIONS.QUOTES_UPDATE,
        PERMISSIONS.QUOTES_SEND,
        PERMISSIONS.QUOTES_APPROVE,
        PERMISSIONS.QUOTES_REJECT,
        PERMISSIONS.QUOTES_CONVERT,

        PERMISSIONS.INVOICES_VIEW,
        PERMISSIONS.INVOICES_CREATE,
        PERMISSIONS.INVOICES_UPDATE,
        PERMISSIONS.INVOICES_ISSUE,
        PERMISSIONS.INVOICES_VOID,
        PERMISSIONS.PAYMENTS_VIEW,
        PERMISSIONS.PAYMENTS_CREATE,

        PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
        PERMISSIONS.REPORTS_VIEW_FINANCIAL,
        PERMISSIONS.REPORTS_VIEW_TECHNICIAN,
        PERMISSIONS.REPORTS_EXPORT,
    ],

    DISPATCHER: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.SERVICE_CATALOG_VIEW,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_CREATE,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_TRANSFER,
        PERMISSIONS.ASSETS_STATUS_CHANGE,

        PERMISSIONS.PARTS_VIEW,
        PERMISSIONS.INVENTORY_VIEW,
        PERMISSIONS.INVENTORY_TRANSFER,
        PERMISSIONS.INVENTORY_RESERVE,
        PERMISSIONS.INVENTORY_CONSUME,
        PERMISSIONS.INVENTORY_RETURN,
        PERMISSIONS.INVENTORY_LOCATIONS_VIEW,

        PERMISSIONS.QUOTES_VIEW,
        PERMISSIONS.QUOTES_CREATE,
        PERMISSIONS.QUOTES_UPDATE,
        PERMISSIONS.QUOTES_SEND,
        PERMISSIONS.QUOTES_CONVERT,

        PERMISSIONS.INVOICES_VIEW,
        PERMISSIONS.INVOICES_CREATE,
        PERMISSIONS.INVOICES_ISSUE,
        PERMISSIONS.PAYMENTS_VIEW,

        PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
        PERMISSIONS.REPORTS_VIEW_TECHNICIAN,
    ],

    TECHNICIAN: [
        PERMISSIONS.CUSTOMERS_VIEW,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_COMPLETE,

        PERMISSIONS.SCHEDULER_VIEW,

        PERMISSIONS.SERVICE_CATALOG_VIEW,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_STATUS_CHANGE,

        PERMISSIONS.PARTS_VIEW,
        PERMISSIONS.INVENTORY_VIEW,
        PERMISSIONS.INVENTORY_CONSUME,
        PERMISSIONS.INVENTORY_RETURN,
        PERMISSIONS.INVENTORY_LOCATIONS_VIEW,

        PERMISSIONS.REPORTS_VIEW_TECHNICIAN,
    ],

    ACCOUNTANT: [
        PERMISSIONS.CUSTOMERS_VIEW,

        PERMISSIONS.WORK_ORDERS_VIEW,

        PERMISSIONS.SERVICE_CATALOG_VIEW,

        PERMISSIONS.ASSETS_VIEW,

        PERMISSIONS.BILLING_VIEW,
        PERMISSIONS.BILLING_MANAGE,

        PERMISSIONS.PARTS_VIEW,
        PERMISSIONS.INVENTORY_VIEW,

        PERMISSIONS.QUOTES_VIEW,

        PERMISSIONS.INVOICES_VIEW,
        PERMISSIONS.INVOICES_CREATE,
        PERMISSIONS.INVOICES_UPDATE,
        PERMISSIONS.INVOICES_ISSUE,
        PERMISSIONS.INVOICES_VOID,
        PERMISSIONS.PAYMENTS_VIEW,
        PERMISSIONS.PAYMENTS_CREATE,
        PERMISSIONS.PAYMENTS_VOID,

        PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
        PERMISSIONS.REPORTS_VIEW_FINANCIAL,
        PERMISSIONS.REPORTS_EXPORT,
    ],
};