import type {
    MembershipRole,
} from "@/generated/prisma/client";

import {
    PERMISSIONS,
    type Permission,
} from "./permissions";

const FULL_PERMISSIONS: Permission[] =
    Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<
    MembershipRole,
    readonly Permission[]
> = {
    OWNER: FULL_PERMISSIONS,

    ADMIN: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,
        PERMISSIONS.CUSTOMERS_DELETE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,
        PERMISSIONS.WORK_ORDERS_COMPLETE,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.MEMBERS_VIEW,
        PERMISSIONS.MEMBERS_INVITE,
        PERMISSIONS.MEMBERS_UPDATE,
        PERMISSIONS.MEMBERS_REMOVE,

        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_UPDATE,

        PERMISSIONS.BILLING_VIEW,
        PERMISSIONS.BILLING_MANAGE,
    ],

    MANAGER: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,
        PERMISSIONS.WORK_ORDERS_COMPLETE,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.MEMBERS_VIEW,

        PERMISSIONS.SETTINGS_VIEW,
    ],

    DISPATCHER: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,
    ],

    TECHNICIAN: [
        PERMISSIONS.CUSTOMERS_VIEW,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_COMPLETE,

        PERMISSIONS.SCHEDULER_VIEW,
    ],

    ACCOUNTANT: [
        PERMISSIONS.CUSTOMERS_VIEW,

        PERMISSIONS.WORK_ORDERS_VIEW,

        PERMISSIONS.BILLING_VIEW,
        PERMISSIONS.BILLING_MANAGE,
    ],
};