import type {
    MembershipRole,
} from "@/generated/prisma/client";

import {
    PERMISSIONS,
    type Permission,
} from "./permissions";

const FULL_PERMISSIONS: Permission[] =
    Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<
    MembershipRole,
    readonly Permission[]
> = {
    OWNER: FULL_PERMISSIONS,

    ADMIN: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,
        PERMISSIONS.CUSTOMERS_DELETE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,
        PERMISSIONS.WORK_ORDERS_COMPLETE,
        PERMISSIONS.WORK_ORDERS_DELETE,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.MEMBERS_VIEW,
        PERMISSIONS.MEMBERS_INVITE,
        PERMISSIONS.MEMBERS_UPDATE,
        PERMISSIONS.MEMBERS_REMOVE,

        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_UPDATE,

        PERMISSIONS.SERVICE_CATALOG_VIEW,
        PERMISSIONS.SERVICE_CATALOG_CREATE,
        PERMISSIONS.SERVICE_CATALOG_UPDATE,
        PERMISSIONS.SERVICE_CATALOG_DELETE,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_CREATE,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_TRANSFER,
        PERMISSIONS.ASSETS_STATUS_CHANGE,
        PERMISSIONS.ASSETS_RETIRE,
        PERMISSIONS.ASSETS_DELETE,
        PERMISSIONS.ASSET_CATEGORIES_MANAGE,

        PERMISSIONS.BILLING_VIEW,
        PERMISSIONS.BILLING_MANAGE,
    ],

    MANAGER: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,
        PERMISSIONS.WORK_ORDERS_COMPLETE,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.MEMBERS_VIEW,

        PERMISSIONS.SETTINGS_VIEW,

        PERMISSIONS.SERVICE_CATALOG_VIEW,
        PERMISSIONS.SERVICE_CATALOG_CREATE,
        PERMISSIONS.SERVICE_CATALOG_UPDATE,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_CREATE,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_TRANSFER,
        PERMISSIONS.ASSETS_STATUS_CHANGE,
        PERMISSIONS.ASSETS_RETIRE,
        PERMISSIONS.ASSET_CATEGORIES_MANAGE,
    ],

    DISPATCHER: [
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_UPDATE,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_CREATE,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_ASSIGN,

        PERMISSIONS.SCHEDULER_VIEW,
        PERMISSIONS.SCHEDULER_CREATE,
        PERMISSIONS.SCHEDULER_UPDATE,
        PERMISSIONS.SCHEDULER_DELETE,

        PERMISSIONS.SERVICE_CATALOG_VIEW,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_CREATE,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_TRANSFER,
        PERMISSIONS.ASSETS_STATUS_CHANGE,
    ],

    TECHNICIAN: [
        PERMISSIONS.CUSTOMERS_VIEW,

        PERMISSIONS.WORK_ORDERS_VIEW,
        PERMISSIONS.WORK_ORDERS_UPDATE,
        PERMISSIONS.WORK_ORDERS_COMPLETE,

        PERMISSIONS.SCHEDULER_VIEW,

        PERMISSIONS.SERVICE_CATALOG_VIEW,

        PERMISSIONS.ASSETS_VIEW,
        PERMISSIONS.ASSETS_UPDATE,
        PERMISSIONS.ASSETS_STATUS_CHANGE,
    ],

    ACCOUNTANT: [
        PERMISSIONS.CUSTOMERS_VIEW,

        PERMISSIONS.WORK_ORDERS_VIEW,

        PERMISSIONS.SERVICE_CATALOG_VIEW,

        PERMISSIONS.ASSETS_VIEW,

        PERMISSIONS.BILLING_VIEW,
        PERMISSIONS.BILLING_MANAGE,
    ],
};