import { PERMISSIONS } from "@/lib/services/authorization/permissions";
import type { MetricDefinition } from "../reporting.types";
import { registerMetric } from "../metricRegistry";

export const FINANCIAL_DIMENSIONS = [
  "customer",
  "invoiceStatus",
  "paymentMethod",
  "time.day",
  "time.week",
  "time.month",
  "time.quarter",
  "time.year",
] as const;

export const financialMetricDefinitions: readonly MetricDefinition[] = [
  {
    key: "invoices.invoicedRevenue",
    category: "FINANCIAL",
    valueType: "SUM_MONEY",
    temporality: "PERIOD",
    sourceModel: "Invoice",
    dateAnchor: { model: "Invoice", field: "issuedAt" },
    baseWhere: () => ({
      status: { in: ["ISSUED", "PARTIALLY_PAID", "PAID", "OVERDUE"] },
    }),
    aggregation: { kind: "SUM", field: "total" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Sum of total invoiced amounts (tax-inclusive snapshot total) for invoices issued during the reporting period (anchored on write-once issuedAt, excluding DRAFT and VOID).",
  },
  {
    key: "invoices.issuedCount",
    category: "FINANCIAL",
    valueType: "COUNT",
    temporality: "PERIOD",
    sourceModel: "Invoice",
    dateAnchor: { model: "Invoice", field: "issuedAt" },
    baseWhere: () => ({
      status: { in: ["ISSUED", "PARTIALLY_PAID", "PAID", "OVERDUE"] },
    }),
    aggregation: { kind: "COUNT" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description:
      "Count of invoices issued during the reporting period (anchored on write-once issuedAt, excluding DRAFT and VOID).",
  },
  {
    key: "invoices.voidedCount",
    category: "FINANCIAL",
    valueType: "COUNT",
    temporality: "PERIOD",
    sourceModel: "Invoice",
    dateAnchor: { model: "Invoice", field: "voidedAt" },
    baseWhere: () => ({ status: "VOID" }),
    aggregation: { kind: "COUNT" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description:
      "Count of invoices voided during the reporting period (anchored on write-once voidedAt with status = VOID).",
  },
  {
    key: "invoices.voidedTotal",
    category: "FINANCIAL",
    valueType: "SUM_MONEY",
    temporality: "PERIOD",
    sourceModel: "Invoice",
    dateAnchor: { model: "Invoice", field: "voidedAt" },
    baseWhere: () => ({ status: "VOID" }),
    aggregation: { kind: "SUM", field: "total" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Total monetary value of invoices voided during the reporting period (anchored on write-once voidedAt with status = VOID).",
  },
  {
    key: "payments.collectedRevenue",
    category: "FINANCIAL",
    valueType: "SUM_MONEY",
    temporality: "PERIOD",
    sourceModel: "Payment",
    dateAnchor: { model: "Payment", field: "paymentDate" },
    baseWhere: () => ({ status: "RECORDED" }),
    aggregation: { kind: "SUM", field: "amount" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Sum of payments collected (Payment.amount) during the reporting period where status = RECORDED (anchored on paymentDate).",
  },
  {
    key: "payments.collectedCount",
    category: "FINANCIAL",
    valueType: "COUNT",
    temporality: "PERIOD",
    sourceModel: "Payment",
    dateAnchor: { model: "Payment", field: "paymentDate" },
    baseWhere: () => ({ status: "RECORDED" }),
    aggregation: { kind: "COUNT" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description:
      "Count of payments collected during the reporting period where status = RECORDED (anchored on paymentDate).",
  },
  {
    key: "invoices.outstandingBalance",
    category: "FINANCIAL",
    valueType: "SUM_MONEY",
    temporality: "AS_OF",
    sourceModel: "Invoice",
    dateAnchor: null,
    baseWhere: () => ({
      status: { in: ["ISSUED", "PARTIALLY_PAID", "OVERDUE"] },
      amountDue: { gt: 0 },
    }),
    aggregation: { kind: "SUM", field: "amountDue" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Sum of current unpaid balances (Invoice.amountDue) as of now for open invoices (status in [ISSUED, PARTIALLY_PAID, OVERDUE] and amountDue > 0).",
  },
  {
    key: "invoices.overdueBalance",
    category: "FINANCIAL",
    valueType: "SUM_MONEY",
    temporality: "AS_OF",
    sourceModel: "Invoice",
    dateAnchor: null,
    baseWhere: () => ({
      status: { in: ["ISSUED", "PARTIALLY_PAID", "OVERDUE"] },
      amountDue: { gt: 0 },
    }),
    aggregation: { kind: "SUM", field: "amountDue" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Sum of current unpaid balances (Invoice.amountDue) as of now for open invoices past their due date (status in [ISSUED, PARTIALLY_PAID, OVERDUE], amountDue > 0, dueDate < asOfUtc).",
  },
  {
    key: "invoices.avgDaysToPayment",
    category: "FINANCIAL",
    valueType: "AVG_DAYS",
    temporality: "PERIOD",
    sourceModel: "Invoice",
    dateAnchor: { model: "Invoice", field: "paidAt" },
    baseWhere: () => ({ status: "PAID", paidAt: { not: null }, issuedAt: { not: null } }),
    aggregation: { kind: "CUSTOM", compute: "avgDaysBetween(issuedAt, paidAt)" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Average number of days elapsed between invoice write-once issuedAt and paidAt for invoices fully paid within the reporting period (anchored on write-once paidAt). Returns null if 0 paid invoices.",
  },
  {
    key: "invoices.countByStatus",
    category: "FINANCIAL",
    valueType: "COUNT",
    temporality: "PERIOD",
    sourceModel: "Invoice",
    dateAnchor: { model: "Invoice", field: "issuedAt" },
    baseWhere: () => ({}),
    aggregation: { kind: "COUNT" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description:
      "Deferred to 501: Invoice status is a mutable state machine column that reflects current lifecycle state rather than an immutable point-in-time event log.",
    deferredReason:
      'Metric "invoices.countByStatus" cannot be computed as a historical period metric: Invoice status is a mutable state machine column that reflects current lifecycle state rather than an immutable point-in-time status event log (Phase 1.14.6 constraint).',
  },
  {
    key: "invoices.collectionRate",
    category: "FINANCIAL",
    valueType: "RATE_PERCENT",
    temporality: "PERIOD",
    sourceModel: "Payment",
    dateAnchor: { model: "Payment", field: "paymentDate" },
    baseWhere: () => ({}),
    aggregation: {
      kind: "RATE",
      numerator: "payments.collectedRevenue",
      denominator: "invoices.invoicedRevenue",
    },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Deferred to 501: Cohort-based collection rate requires tracing payment allocations strictly to invoices issued within the cohort period to avoid prior-period cash inflation.",
    deferredReason:
      'Metric "invoices.collectionRate" cannot be computed: Cohort-based collection rate requires tracing payment allocations strictly to invoices issued within the cohort period to avoid prior-period cash inflation (Phase 1.14.6 constraint).',
  },
  {
    key: "quotes.pipelineTotal",
    category: "FINANCIAL",
    valueType: "SUM_MONEY",
    temporality: "PERIOD",
    sourceModel: "Quote",
    dateAnchor: { model: "Quote", field: "createdAt" },
    baseWhere: () => ({ status: "PENDING" }),
    aggregation: { kind: "SUM", field: "total" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description:
      "Total monetary value of pending quotes created within the period (pipeline snapshot).",
  },
  {
    key: "quotes.createdCount",
    category: "FINANCIAL",
    valueType: "COUNT",
    temporality: "PERIOD",
    sourceModel: "Quote",
    dateAnchor: { model: "Quote", field: "createdAt" },
    baseWhere: () => ({}),
    aggregation: { kind: "COUNT" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description: "Total count of quotes created during the period.",
  },
  {
    key: "quotes.approvedCount",
    category: "FINANCIAL",
    valueType: "COUNT",
    temporality: "PERIOD",
    sourceModel: "Quote",
    dateAnchor: { model: "Quote", field: "createdAt" },
    baseWhere: () => ({ status: "APPROVED" }),
    aggregation: { kind: "COUNT" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description: "Total count of approved quotes created during the period.",
  },
  {
    key: "quotes.rejectedCount",
    category: "FINANCIAL",
    valueType: "COUNT",
    temporality: "PERIOD",
    sourceModel: "Quote",
    dateAnchor: { model: "Quote", field: "createdAt" },
    baseWhere: () => ({ status: "REJECTED" }),
    aggregation: { kind: "COUNT" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description: "Total count of rejected quotes created during the period.",
  },
  {
    key: "quotes.approvedTotal",
    category: "FINANCIAL",
    valueType: "SUM_MONEY",
    temporality: "PERIOD",
    sourceModel: "Quote",
    dateAnchor: { model: "Quote", field: "createdAt" },
    baseWhere: () => ({ status: "APPROVED" }),
    aggregation: { kind: "SUM", field: "total" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: true,
    materializationTrigger: null,
    description: "Total monetary amount of approved quotes created during the period.",
  },
  {
    key: "quotes.winRate",
    category: "FINANCIAL",
    valueType: "RATE_PERCENT",
    temporality: "PERIOD",
    sourceModel: "Quote",
    dateAnchor: { model: "Quote", field: "createdAt" },
    baseWhere: () => ({}),
    aggregation: { kind: "RATE", numerator: "quotes.approvedCount", denominator: "quotes.createdCount" },
    requiredPermission: PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    supportedDimensions: FINANCIAL_DIMENSIONS,
    isSnapshotDerived: false,
    materializationTrigger: null,
    description: "Rate of approved quotes divided by total created quotes in the period.",
  },
];

// Register all financial metric definitions
for (const metric of financialMetricDefinitions) {
  registerMetric(metric);
}
